version: '3'
services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: kanban
    volumes:
      - kanban-mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

  kanban-postgres:
    image: "postgres:9.6-alpine"
    container_name: kanban-postgres
    restart: always

    volumes:
      - kanban-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=kanban
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban

  kanban-app:
    build: ./kanban-app
    container_name: kanban-app
    restart: always

    environment:
      - MONGO_SERVER=mongo
      - MONGO_DB=kanban
      - MONGO_USER=kanban
      - MONGO_PASSWORD=kanban
      - POSTGRES_SERVER=kanban-postgres
      - POSTGRES_DB=kanban
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban
    ports:
      - 8080:8080
    depends_on:
      - kanban-postgres
      - rabbitmq
    volumes:
      - kanban-images:/images
    links:
      - kanban-postgres
  kanban-ui:
    build: ./kanban-ui
    restart: always

    container_name: kanban-ui
    ports:
      - 5000:80
    depends_on:
      - kanban-app
    links:
      - kanban-app
  rabbitmq:
    restart: always
    image: 'rabbitmq:3-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - "5672:5672" # RabbitMQ AMQP port
      - "15672:15672" # RabbitMQ management console
      - "15674:15674" # RabbitMQ stomp
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_web_stomp && rabbitmq-server"

volumes:
  kanban-data:
    driver: local
  kanban-mongo:
    driver: local
  kanban-images:
    driver: local