provider:
  name: openfaas
  gateway: http://10.105.13.131:8080/
functions:
  fn1:
    lang: python3
    handler: ./fn1
    image: coden256/fn1:latest
    build_options: 
      - dev
    annotations:
      topic: cron-function
      schedule: "*/5 * * * *"

