server.servlet.context-path: /api

app:
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    configuration:
      maximum-pool-size: 30

  mongoDatasource:
    url: mongodb://mongodb/docker-db