server.servlet.context-path: /api

spring:
  datasource:
    url:  jdbc:postgresql://${POSTGRES_SERVER}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase.change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true

