server.servlet.context-path: /api

spring:
  datasource:
    url:  jdbc:postgresql://${POSTGRES_SERVER}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  mongoDatasource:
    url: mongodb://mongodb/docker-db