server.servlet.context-path: /api

app:
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    configuration:
      maximum-pool-size: 30


spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_SERVER}/${MONGO_DB}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      authentication-database: kanban

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
