version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:8080
functions:
  email-notifier:
    lang: python3
    handler: ./email-notifier
    image: coden256/email-notifier:latest

  pwd-reader:
    lang: python3
    handler: ./pwd-reader
    image: coden256/pwd-reader:latest

  pwd-writer:
    lang: python3
    handler: ./pwd-writer
    image: coden256/pwd-writer:latest

