version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  email:
    lang: python3
    handler: ./email
    image: coden256/email:latest
    #annotations:
    #  topic: cron-function
    #  schedule: "*/1 * * * *"

  incrementer:
    lang: python3-flask
    handler: ./incrementer
    image: coden256/incrementer:latest

  time:
    lang: python3
    handler: ./time
    image: coden256/time:latest

  random-fn:
    lang: python3
    handler: ./random-fn
    image: coden256/random-fn:latest
    environment:
      functions: incrementer, time, figlet, random-fn, nodeinfo
