version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  email-notifier:
    lang: python3
    handler: ./email-notifier
    image: coden256/email-notifier:latest
    annotations:
      topic: cron-function
      schedule: "*/1 * * * *"

  pwd-reader:
    lang: python3
    handler: ./pwd-reader
    image: coden256/pwd-reader:latest

  pwd-writer:
    lang: python3
    handler: ./pwd-writer
    image: coden256/pwd-writer:latest

